version: '3.0'
services:
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - mysql-blog:/var/lib/mysql
    app:
        restart: unless-stopped
        container_name: php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/var/www
        environment:
            DB_HOST: "mysql"
            DB_DATABASE: '${DB_DATABASE}'
            DB_USERNAME: '${DB_USERNAME}'
            DB_PASSWORD: '${DB_PASSWORD}'
    webserver:
        image: nginx:1.10.0-alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    queue:
        build:
            context: .
            dockerfile: docker/supervisor/Dockerfile
        container_name: queue
        volumes:
            - ./:/var/www
        links:
            - app
            - webserver
volumes:
    mysql-blog:
        driver: local
